# Generated by Django 3.0.7 on 2020-06-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_set', '0004_auto_20200629_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='completed',
        ),
    ]
