# Generated by Django 3.0.7 on 2020-07-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_set', '0007_auto_20200629_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
